### ISSUE TITLE
" easy way to underline a row 

### ISSUE THREAD

**Issue by voyeg3r** [derekwyatt/vim-config#7]
Sorry to bother you but I think you will like it:
nmap <silent> ,u :t.<cr>Vr=k

insted of:

nmap <silent> ,u= :t.\|s/./=/g\|:nohls<cr>
Once we don't have search involved we don't need to use "nohls". Instead we use V to select the line "r=" to replace and "k" to go back

**Comment by derekwyatt** [comment]
Yup, but that's just a different way to do the same thing I'm doing and what I'm doing ain't broke :)
